name: Ticket Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs the script every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 pushbullet.py

    - name: Run Script
      run: |
        python tktscraper.py
